[build]
  command   = "npm ci && npm run build"
  publish   = "dist"
  node_version = "18"

# SPA fallback so deep-links work
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# (Optional) Proxy API requests to your LAMP backend
# Replace with your backend URL (HTTPS strongly recommended)
[[redirects]]
  from = "/api/*"
  to   = "https://api.your-domain.com/:splat"
  status = 200
  force = true

# PWA + security headers
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options    = "nosniff"
    X-Frame-Options           = "DENY"
    Referrer-Policy           = "no-referrer-when-downgrade"
    Content-Security-Policy   = "default-src 'self'; img-src 'self' data: blob:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.your-domain.com; manifest-src 'self';"
